#!/usr/bin/env Rscript

options(stringsAsFactors = FALSE)

script_path <- function() {
  argument <- grep("^--file=", commandArgs(trailingOnly = FALSE), value = TRUE)
  if (!length(argument)) return(normalizePath(".", winslash = "/"))
  normalizePath(sub("^--file=", "", argument[[1L]]), winslash = "/")
}

script_dir <- dirname(script_path())
output_dir <- file.path(script_dir, "output")
table_dir <- file.path(script_dir, "tables")
dir.create(table_dir, recursive = TRUE, showWarnings = FALSE)

pilot <- "--pilot" %in% commandArgs(trailingOnly = TRUE)
unknown <- setdiff(commandArgs(trailingOnly = TRUE), "--pilot")
if (length(unknown)) stop("Unknown option: ", unknown[[1L]], call. = FALSE)

prefix <- if (pilot) "pilot_" else ""
input_path <- file.path(
  output_dir,
  paste0(prefix, "CCMM_2026_wp--computation.rds")
)
if (!file.exists(input_path)) {
  stop("Missing computational benchmark: ", input_path, call. = FALSE)
}
object <- readRDS(input_path)
if (!is.list(object) || !is.data.frame(object$results)) {
  stop("Invalid computational benchmark object.", call. = FALSE)
}

median_value <- function(data, variable) {
  stats::median(data[[variable]], na.rm = TRUE)
}

format_integer <- function(value) {
  format(round(value), big.mark = ",", scientific = FALSE, trim = TRUE)
}

format_seconds <- function(value) {
  if (!is.finite(value)) return("--")
  if (value < 0.005) "$<0.01$" else formatC(value, digits = 2L, format = "f")
}

write_table <- function(lines, filename) {
  path <- file.path(table_dir, paste0(prefix, filename))
  writeLines(lines, path, useBytes = TRUE)
  message("Wrote table: ", path)
}

results <- object$results

aom <- results[results$model == "AOM", , drop = FALSE]
aom_rows <- lapply(sort(unique(aom$universe_size)), function(universe_size) {
  current <- aom[aom$universe_size == universe_size, , drop = FALSE]
  feasibility <- current[current$query == "feasibility", , drop = FALSE]
  all_pairs <- current[current$query == "all-pairs", , drop = FALSE]
  paste0(
    universe_size, " & ",
    format_integer(unique(current$n_menus)), " & ",
    format_integer(unique(current$n_inequalities)), " & ",
    format_integer(unique(current$n_possible_rankings)), " & ",
    format_integer(unique(current$n_binary_variables)), " & ",
    format_integer(unique(current$n_constraints)), " & ",
    format_seconds(median_value(feasibility, "construction_seconds")), " & ",
    format_seconds(median_value(feasibility, "elapsed_seconds")), " & ",
    format_seconds(median_value(all_pairs, "elapsed_seconds")), " \\\\"
  )
})

write_table(c(
  "\\begin{table}[t]",
  "\\centering",
  "\\caption{Deterministic computational benchmark for homogeneous AOM}",
  "\\label{tab:computation-aom}",
  "\\resizebox{\\textwidth}{!}{%",
  "\\begin{tabular}{rrrrrrrrr}",
  "\\toprule",
  "$|X|$ & $|\\mathcal D|$ & $\\mathfrak c_\\succ$ & $|X|!$ & Binary & Constraints & Build & Feasibility & All pairs \\\\",
  "\\midrule",
  unlist(aom_rows),
  "\\bottomrule",
  "\\end{tabular}%",
  "}",
  "\\begin{flushleft}",
  paste0(
    "\\footnotesize Notes: Times are median elapsed seconds over ",
    object$options$repetitions,
    " runs. The column $\\mathfrak c_\\succ$ counts the nonredundant fixed-preference inequalities used for inference. Constraints counts the direct mixed-integer rows retained by the software, including totality, transitivity, and algebraically redundant regularity rows. Build is the time spent validating the population and constructing this system in the feasibility-only call. Feasibility includes system construction and one solver call. All pairs includes system construction, the feasibility solve, and one reverse-comparison query for every unordered pair. The deterministic choice system is generated by full attention and the ordering $1\\succ2\\succ\\cdots\\succ|X|$ on the complete menu domain."
  ),
  "\\end{flushleft}",
  "\\end{table}"
), "CCMM_2026_wp--table-computation-aom.tex")

hlao <- results[results$model == "H-LAO", , drop = FALSE]
hlao_rows <- lapply(sort(unique(hlao$universe_size)), function(universe_size) {
  current <- hlao[hlao$universe_size == universe_size, , drop = FALSE]
  enumeration <- current[current$query == "enumeration", , drop = FALSE]
  generated <- current[current$query == "column-generation", , drop = FALSE]
  paste0(
    universe_size, " & ",
    format_integer(unique(current$n_menus)), " & ",
    format_integer(unique(current$n_choice_equations)), " & ",
    format_integer(unique(current$n_possible_rankings)), " & ",
    format_integer(unique(enumeration$n_columns)), " & ",
    format_integer(stats::median(generated$n_active_columns)), " & ",
    format_integer(unique(generated$n_binary_variables)), " & ",
    format_seconds(median_value(enumeration, "elapsed_seconds")), " & ",
    format_seconds(median_value(generated, "elapsed_seconds")), " & ",
    if (all(generated$certified)) "Yes" else "No",
    " \\\\"
  )
})

write_table(c(
  "\\begin{table}[t]",
  "\\centering",
  "\\caption{Deterministic computational benchmark for H-LAO}",
  "\\label{tab:computation-hlao}",
  "\\resizebox{\\textwidth}{!}{%",
  "\\begin{tabular}{rrrrrrrrrc}",
  "\\toprule",
  "$|X|$ & $|\\mathcal D|$ & Choice eq. & $|X|!$ & Enumerated & Active & Pricing binary & Enumeration & Column generation & Certified \\\\",
  "\\midrule",
  unlist(hlao_rows),
  "\\bottomrule",
  "\\end{tabular}%",
  "}",
  "\\begin{flushleft}",
  paste0(
    "\\footnotesize Notes: Times are median elapsed seconds over ",
    object$options$repetitions,
    " runs. The deterministic suffix-domain system has outside-option probability $0.2$ and selects the first listed alternative with probability $0.8$. Both methods bound the event that alternative 1 is top ranked. Active is the number of ranking columns retained by column generation. Certified requires successful master and pricing statuses and all residual, reduced-cost, and gap checks at the reported tolerance."
  ),
  "\\end{flushleft}",
  "\\end{table}"
), "CCMM_2026_wp--table-computation-hlao.tex")
